name: run some pythong

on:
  schedule:
    - cron: "0 0 * * *" #runs at 00:00 UTC everyday
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - name: execute py script before checkout
        run: |
          python3 -c "import os; print(os.listdir())"

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.

      - name: execute py script after checkout
        run: |
          python3 -c "import os; print(os.listdir())"
#        env:
#          key: ${{ secrets.key }} # if run.py requires passwords..etc, set it as secrets
