name: run some pythong

on:
  # schedule:
  #   - cron: "0 0 * * *" #runs at 00:00 UTC everyday
  # workflow_dispatch:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed

      - run: |
          python3 -c "import os; print(os.listdir())"

      - uses: actions/checkout@v3 # checkout the repository content to github runner.
        with:
          #repository: ''
          path: 'poop'

      - run: |
          python3 -c "import os; print(os.listdir())"




#        env:
#          key: ${{ secrets.key }} # if run.py requires passwords..etc, set it as secrets
